export const types = {
    SEARCH_BOOK: 'SEARCH_BOOK',
    SEARCH_BOOK_SUCCESS: 'SEARCH_BOOK_SUCCESS',
    ADD_TO_FAVORITE: 'ADD_TO_FAVORITE',
    REMOVE_TO_FAVORITE: 'REMOVE_TO_FAVORITE',
    IS_LOADING: 'IS_LOADING',
    IS_KEYBOARD_OPEN: 'IS_KEYBOARD_OPEN',
    LOAD_MORE_BOOK: 'LOAD_MORE_BOOK',
    IS_MORE_LOADING: 'IS_MORE_LOADING',
    CLEAR_SEARCH_HISTORY: 'CLEAR_SEARCH_HISTORY'
}